# Site settings
baseURL = "//komogfestmedos.com"
languageCode = "en-US"
title = "Gitte og Thomas Kobberbryllup"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2019 Gitte ❤ Thomas"

[params]

  # Metadata for search engines and social sharing
  author = "Thomas Gilbert"
  description = "Invitation til vores Kobberbryllup."
  shareImage = "images/social.jpg"
  twitterHandle = "thomasbjgilbert"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.gif"
      position = "center center"

    # Video
    [params.visual.video]
      enable = true
      mute = true
      file = "videos/background.gif"
      # youtubeId = "dk9uNWPP7EA"

  # Links List #3
  [[params.links]]
    [params.links.list1]
      heading = "Vælg nedenfor:"

      [[params.links.list1.link]]
        text = "Link til Tilmelding"
        url = "https://forms.gle/KxuW7Jc33fXETn9y9"

      [[params.links.list1.link]]
        text = "Link til Gaveidéer"
        url = "https://docs.google.com/presentation/d/e/2PACX-1vS2JHuY7KVbtZU1j8_siIllfjaS_HDDQ12djuSQ_SwB9MUI_Rivv0QFH2A8_qAeOCuDCr8LULe6GU5A/pub?start=true&loop=true&delayms=30000"
