# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Kobberbryllup"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/escalate/hugo-split-theme/blob/master/LICENSE.md"
description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
homepage = "//github.com/escalate/hugo-split-theme"
tags = ["minimal", "onepage", "one page", "responsive", "personal"]
features = []
min_version = "0.21"

[author]
  name = "Gitte og Thomas"

# Copyright
copyright = "&copy;2018 Your Name"


[[params.visual.image]]
  enable = true
  file = "images/tn.jpg"
  position = "center center"